name = input("Enter your name:\n")
print(name + "'s Playlist yay")

print("1. African Dance Music")
print("2. Catch Me Outside Radio")
print("3. cardi b")
print("4. zonnique radio")
print("5. mexican radio")
print("6. blackpanther")
print("7. mr.hotspot")
print("8. trap queen")
print("9. my life be like")
print("10. gotta be quicker than that")
print("11. walk it like talk it")
print("12. dust on the bottle")
print("13. dirt on my boots")
print("14. boop")
print("15. ciara")